#include <iostream>
#include <iomanip>
#include <locale>



void SCEprint(){

  // read the Tree generated by tree1w and fill two histograms
  // note that we use "new" to create the TFile and TTree objects,
  // to keep them alive after leaving this function.


  TFile *f = new TFile("ntuple.root");
  TTree *tt = (TTree*)f->Get("GenAnalyzer/emJetTree");

  Int_t event;

  vector<int> *genpart_index=new vector<int>;
  vector<float> *genpart_pt = new vector<float>;
  vector<float> *genpart_eta = new vector<float>;
  vector<float> *genpart_phi = new vector<float>;
  vector<int> *genpart_pid = new vector<int>;




  tt->SetBranchAddress("event",&event);
  tt->SetBranchAddress("genpart_index",&genpart_index);
  tt->SetBranchAddress("genpart_pt",&genpart_pt);
  tt->SetBranchAddress("genpart_eta",&genpart_eta);
  tt->SetBranchAddress("genpart_phi",&genpart_phi);
  tt->SetBranchAddress("genpart_pid",&genpart_pid);


  // create a histograms
  TH1F *hptdp   = new TH1F("hptdp","dark pion pt distribution",100,0.,500.);
  TH1F *hptdq   = new TH1F("hptdq","dark quark pt distribution",100,0.,500.);


  //read all entries and fill the histograms
  Int_t nentries = (Int_t)tt->GetEntries();
  for (Int_t i=0; i<nentries; i++) {
    tt->GetEntry(i);
    cout<<"event number is "<<event<<endl;
    //genpart variables
    for(Int_t j=0; j<(*genpart_index).size(); j++) {
      cout<<" genpart "<<(*genpart_pt)[j]<<endl;
      if(abs((*genpart_pid)[j])==4900111){
	hptdp->Fill((*genpart_pt)[j]);
      }
      if(abs((*genpart_pid)[j])==4900101){
	hptdq->Fill((*genpart_pt)[j]);
      }

    }
  }
  // We do not close the file. We want to keep the generated
  // histograms we open a browser and the TreeViewer
  if (gROOT->IsBatch()) return;
  TCanvas *c1 = new TCanvas("c1","Vertex Plots",200,10,700,500);
  hptdp->Draw();
  //hptdq->Draw();
  c1->Modified();
  c1->Update();
  // t1->StartViewer();

  TFile myfile("haha.root","RECREATE");
  hptdp->Write();
  hptdq->Write();

  tt->ResetBranchAddresses();


  //In the browser, click on "ROOT Files", then on "tree1.root"
  //You can click on the histogram icons in the right panel to draw
  //them in the TreeViewer, follow the instructions in the Help.
}
