#include <iostream>
#include <iomanip>
#include <locale>



void SCEprint(){

  // read the Tree generated by tree1w and fill two histograms
  // note that we use "new" to create the TFile and TTree objects,
  // to keep them alive after leaving this function.


  TFile *f = new TFile("ntuple.root");
  TTree *tt = (TTree*)f->Get("emJetAnalyzer/emJetTree");

  Int_t nVtx, event;
  Float_t met_pt, met_phi;

  vector<int> *genpart_index=new vector<int>;
  vector<float> *genpart_pt = new vector<float>;

  vector<int> *jet_index=new vector<int>;
  vector<int> *jet_source=new vector<int>;
  vector<float> *jet_pt = new vector<float>;
  vector<float> *jet_eta = new vector<float>;
  vector<float> *jet_phi = new vector<float>;
  vector<float> *jet_alphaMax = new vector<float>;
  vector<vector<float> > *track_pt = 0;
  vector<vector<float> > *track_eta = 0;
  vector<vector<int> > *track_index = 0;
  vector<vector<int> > *track_jet_index = 0;
  vector<vector<int> > *track_vertex_index = 0;
  vector<vector<int> > *track_algo = 0;
  vector<vector<float> > *track_vertex_weight =0;
  vector<vector<float> > *track_ipZ =0;



  tt->SetBranchAddress("nVtx",&nVtx);
  tt->SetBranchAddress("event",&event);
  tt->SetBranchAddress("met_pt",&met_pt);
  tt->SetBranchAddress("met_phi",&met_phi);
  tt->SetBranchAddress("genpart_index",&genpart_index);
  tt->SetBranchAddress("genpart_pt",&genpart_pt);
  tt->SetBranchAddress("jet_index",&jet_index);
  tt->SetBranchAddress("jet_source",&jet_source);
  tt->SetBranchAddress("jet_pt",&jet_pt);
  tt->SetBranchAddress("jet_eta",&jet_eta);
  tt->SetBranchAddress("jet_phi",&jet_phi);
  tt->SetBranchAddress("jet_alphaMax",&jet_alphaMax);
  tt->SetBranchAddress("track_pt",&track_pt);
  tt->SetBranchAddress("track_eta",&track_eta);
  tt->SetBranchAddress("track_index",&track_index);
  tt->SetBranchAddress("track_jet_index",&track_jet_index);
  tt->SetBranchAddress("track_algo",&track_algo);
  tt->SetBranchAddress("track_vertex_index",&track_vertex_index);
  tt->SetBranchAddress("track_vertex_weight",&track_vertex_weight);
  tt->SetBranchAddress("track_ipZ",&track_ipZ);

  // create a histograms
  TH1F *hpt   = new TH1F("hpt","pt distribution",100,0.,500.);
  TH1F *halpha   = new TH1F("halpha","alphaMax distribution",100,0.,100.);

  //read all entries and fill the histograms
  Int_t nentries = (Int_t)tt->GetEntries();
  for (Int_t i=0; i<nentries; i++) {
    tt->GetEntry(i);
    cout<<"event number is "<<event<<" number of vertex is "<<nVtx<<endl;
    cout<<" pt eta phi alphaMax "<<endl;
    //genpart variables
    for(Int_t j=0; j<(*genpart_index).size(); j++) {
      cout<<" genpart "<<(*genpart_pt)[j]<<endl;
    }
    // jet variables
    for(Int_t j=0; j<(*jet_index).size(); j++) {
      cout<<" jet "<<(*jet_pt)[j]<<" "<<(*jet_eta)[j]<<" "<<(*jet_phi)[j]<<" "<<(*jet_alphaMax)[j]<<" "<<endl;
      hpt->Fill((*jet_pt)[j]);
      halpha->Fill((*jet_alphaMax)[j]);
      vector<float> track_pts = track_pt->at(j);
      vector<float> track_etas = track_eta->at(j);
      vector<int> track_indexs = track_index->at(j);
      vector<int> track_jet_indexs = track_jet_index->at(j);
      vector<int> track_algos = track_algo->at(j);
      vector<int> track_vertex_indexs = track_vertex_index->at(j);
      vector<float> track_vertex_weights = track_vertex_weight->at(j);
      vector<float> track_ipZs = track_ipZ->at(j);
      //      cout<< "pT         eta      index   jetindx    algo    vrtxinx   vtx_w     ipz"<<endl;
      for (unsigned itrack=0; itrack<track_pts.size(); itrack++) {
	/*        cout 
	  <<setw(8)<<setprecision(3)<< track_pts[itrack]<<" "
	  <<setw(8)<<setprecision(3)<< track_etas[itrack]<<" "
	  <<setw(8)<< track_indexs[itrack]<<" "
	  <<setw(8)<< track_jet_indexs[itrack]<<" "
	  <<setw(8)<< track_algos[itrack]<<" "
	  <<setw(8)<< track_vertex_indexs[itrack]<<" "
	  <<setw(8)<< track_vertex_weights[itrack]<<" "
	  <<setw(8)<< track_ipZs[itrack]<<" "
	  <<endl; */
      }
    }
  }
  // We do not close the file. We want to keep the generated
  // histograms we open a browser and the TreeViewer
  if (gROOT->IsBatch()) return;
  //  TCanvas *c1 = new TCanvas("c1","Vertex Plots",200,10,700,500);
  //  hpt->Draw();
  //c1->Modified();
  //c1->Update();
  //  t1->StartViewer();

  tt->ResetBranchAddresses();
  delete jet_index;
  delete jet_source;
  delete jet_pt;
  delete jet_eta;
  delete jet_phi;
  delete jet_alphaMax;
  delete track_pt;
  delete track_eta;
  delete track_index;
  delete track_jet_index;
  delete track_algo;
  delete track_vertex_index;
  delete track_vertex_weight;
  delete track_ipZ;


  //In the browser, click on "ROOT Files", then on "tree1.root"
  //You can click on the histogram icons in the right panel to draw
  //them in the TreeViewer, follow the instructions in the Help.
}
